# Generated by Django 3.2.7 on 2023-01-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='datecompletes',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
