# Generated by Django 3.2.7 on 2023-01-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0004_alter_weight_memo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='title',
            new_name='weight',
        ),
    ]
