# Generated by Django 3.2.7 on 2023-01-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0005_rename_title_weight_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
