# Generated by Django 3.2.7 on 2023-01-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0008_alter_weight_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
