# Generated by Django 3.2.7 on 2023-01-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0009_alter_weight_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='title',
            field=models.CharField(default=False, max_length=25),
        ),
    ]
