# Generated by Django 3.2.7 on 2023-01-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0010_weight_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
